
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '.env') });

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY);

async function inspectNews() {
    // Slug derived from screenshot: tubann-geleneksel-lokum-gnleri-balad-709
    // Note: The slug generated by my bot might differ slightly (random suffix). 
    // I'll search by title or partial slug.

    console.log("Searching for news item...");

    const { data, error } = await supabase
        .from('news')
        .select('*')
        .ilike('title', '%Lokum Günleri%') // "Tuğba’nın ‘Geleneksel Lokum Günleri’ başladı"
        .limit(1);

    if (error) {
        console.error('Error:', error);
        return;
    }

    if (!data || data.length === 0) {
        console.log("No news found with that title.");
        return;
    }

    const item = data[0];
    console.log("Found Item:");
    console.log(`ID: ${item.id}`);
    console.log(`Title: ${item.title}`);
    console.log(`Slug: ${item.slug}`);
    console.log(`Published At: ${item.published_at}`);
    console.log(`Is Active: ${item.is_active}`);
    console.log(`Category (String): ${item.category}`);
    console.log(`Category ID: ${item.category_id}`);

    // Check actual category table
    if (item.category_id) {
        const { data: cat, error: catErr } = await supabase
            .from('categories')
            .select('*')
            .eq('id', item.category_id)
            .single();

        if (cat) {
            console.log(`Linked Category Name: ${cat.name}`);
            console.log(`Linked Category Slug: ${cat.slug}`);
        } else {
            console.log("Linked Category NOT FOUND in categories table.");
        }
    }
}

inspectNews();
